"""RF pulse signature storage and matching helpers."""

from __future__ import annotations

from typing import Any
import json
from pathlib import Path

USER_SIGNATURES_FILE = Path(__file__).resolve().parents[1] / "sessions" / "signatures_user.json"

RF_SIGNATURES: list[dict[str, Any]] = [
    {
        "name": "Shenzhen Wale WL-TH6R Temperature & Humidity Sensor",
        "file": "shenzhen_wale_wl_th6r.c",
        "modulation": "OOK/ASK",
        "short_pulse": 365,
        "long_pulse": 605,
        "gap": 780,
    },
    {
        "name": "Nexa",
        "file": "nexa.c",
        "modulation": "OOK/ASK",
        "short_pulse": 270,
        "long_pulse": 1300,
        "gap": 2650,
    },
    {
        "name": "SimpliSafe Gen 3 Home Security System",
        "file": "simplisafe_gen3.c",
        "modulation": "FSK",
        "short_pulse": 208,
        "long_pulse": 208,
        "gap": 7000,
    },
    {
        "name": "Radiohead ASK",
        "file": "radiohead_ask.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 500,
        "gap": 5,
    },
    {
        "name": "Calibeur RF-104 Sensor",
        "file": "calibeur.c",
        "modulation": "OOK/ASK",
        "short_pulse": 760,
        "long_pulse": 2240,
        "gap": 3200,
    },
    {
        "name": "Fine Offset WH1050 Weather Station",
        "file": "fineoffset_wh1050.c",
        "modulation": "FSK",
        "short_pulse": 544,
        "long_pulse": 1524,
        "gap": 10520,
    },
    {
        "name": "ANT and ANT+ devices",
        "file": "ant_antplus.c",
        "modulation": "FSK",
        "short_pulse": 1,
        "long_pulse": 1,
        "gap": 8,
    },
    {
        "name": "Maverick XR-50 BBQ Sensor",
        "file": "maverick_xr50.c",
        "modulation": "FSK",
        "short_pulse": 107,
        "long_pulse": 107,
        "gap": 2200,
    },
    {
        "name": "Airpuxem TPMS TYH11_EU6_ZQ",
        "file": "tpms_airpuxem.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "Visonic powercode",
        "file": "visonic_powercode.c",
        "modulation": "OOK/ASK",
        "short_pulse": 400,
        "long_pulse": 800,
        "gap": 900,
    },
    {
        "name": "IKEA Sparsnas Energy Meter Monitor",
        "file": "ikea_sparsnas.c",
        "modulation": "FSK",
        "short_pulse": 27,
        "long_pulse": 27,
        "gap": 1000,
    },
    {
        "name": "Fine Offset Electronics WH46 air quality sensor",
        "file": "fineoffset_wh46.c",
        "modulation": "FSK",
        "short_pulse": 58,
        "long_pulse": 58,
        "gap": 2500,
    },
    {
        "name": "Biltema rain gauge",
        "file": "bt_rain.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1940,
        "long_pulse": 3900,
        "gap": 4100,
    },
    {
        "name": "Elro DB286A Doorbell",
        "file": "elro_db286a.c",
        "modulation": "OOK/ASK",
        "short_pulse": 456,
        "long_pulse": 1448,
        "gap": 2000,
    },
    {
        "name": "Alps FWB1U545 Car Remote",
        "file": "alps_fwb1u545.c",
        "modulation": "FSK",
        "short_pulse": 500,
        "long_pulse": None,
        "gap": 1500,
    },
    {
        "name": "Mebus 433",
        "file": "mebus.c",
        "modulation": "OOK/ASK",
        "short_pulse": 800,
        "long_pulse": 1600,
        "gap": 2400,
    },
    {
        "name": "emonTx OpenEnergyMonitor",
        "file": "emontx.c",
        "modulation": "FSK",
        "short_pulse": 2000000,
        "long_pulse": 2000000,
        "gap": 1200,
    },
    {
        "name": "Ecowitt Wireless Outdoor Thermometer WH53/WH0280/WH0281A",
        "file": "ecowitt.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 1480,
        "gap": 1500,
    },
    {
        "name": "Neptune R900 flow meters",
        "file": "neptune_r900.c",
        "modulation": "OOK/ASK",
        "short_pulse": 30,
        "long_pulse": 30,
        "gap": 320,
    },
    {
        "name": "Arad/Master Meter Dialog3G water utility meter",
        "file": "arad_ms_meter.c",
        "modulation": "FSK",
        "short_pulse": 8,
        "long_pulse": 8,
        "gap": 30,
    },
    {
        "name": "Abarth 124 Spider and Shenzhen EGQ Q85 TPMS",
        "file": "tpms_abarth124.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "Digitech XC-0324 / AmbientWeather FT005TH temp/hum sensor",
        "file": "digitech_xc0324.c",
        "modulation": "OOK/ASK",
        "short_pulse": 520,
        "long_pulse": 1000,
        "gap": 3000,
    },
    {
        "name": "GEO minim+ energy monitor",
        "file": "geo_minim.c",
        "modulation": "FSK",
        "short_pulse": 24,
        "long_pulse": 24,
        "gap": 3000,
    },
    {
        "name": "AVE TPMS",
        "file": "tpms_ave.c",
        "modulation": "FSK",
        "short_pulse": 100,
        "long_pulse": 100,
        "gap": 400,
    },
    {
        "name": "Wireless Smoke and Heat Detector GS 558",
        "file": "smoke_gs558.c",
        "modulation": "OOK/ASK",
        "short_pulse": 436,
        "long_pulse": 1202,
        "gap": 1299,
    },
    {
        "name": "Watts WFHT-RF Thermostat",
        "file": "watts_thermostat.c",
        "modulation": "OOK/ASK",
        "short_pulse": 260,
        "long_pulse": 600,
        "gap": 6000,
    },
    {
        "name": "Marlec Solar iBoost+ sensors",
        "file": "marlec_solar.c",
        "modulation": "FSK",
        "short_pulse": 20,
        "long_pulse": 20,
        "gap": 300,
    },
    {
        "name": "Microchip HCS361 KeeLoq Hopping Encoder based remotes (-f 315.1M) (Sync, 833 bit/s)",
        "file": "hcs361.c",
        "modulation": "OOK/ASK",
        "short_pulse": 400,
        "long_pulse": 800,
        "gap": 1200,
    },
    {
        "name": "Eurochron EFTH-800 temperature and humidity sensor",
        "file": "efth800.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": 500,
        "gap": 750,
    },
    {
        "name": "DSC Security Contact",
        "file": "dsc.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": 500,
        "gap": 5000,
    },
    {
        "name": "Honeywell ActivLink, Wireless Doorbell",
        "file": "honeywell_wdb.c",
        "modulation": "FSK",
        "short_pulse": 175,
        "long_pulse": 340,
        "gap": 0,
    },
    {
        "name": "Security+ (Keyfob)",
        "file": "secplus_v1.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 500,
        "gap": 15000,
    },
    {
        "name": "Bresser water leakage",
        "file": "bresser_leakage.c",
        "modulation": "FSK",
        "short_pulse": 124,
        "long_pulse": 124,
        "gap": 25000,
    },
    {
        "name": "Clipsal CMR113 Cent-a-meter power meter",
        "file": "cmr113.c",
        "modulation": "OOK/ASK",
        "short_pulse": 480,
        "long_pulse": 976,
        "gap": 2028,
    },
    {
        "name": "Klimalogg",
        "file": "klimalogg.c",
        "modulation": "OOK/ASK",
        "short_pulse": 26,
        "long_pulse": 0,
        "gap": 0,
    },
    {
        "name": "Hyundai WS SENZOR Remote Temperature Sensor",
        "file": "wssensor.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1000,
        "long_pulse": 2000,
        "gap": 2400,
    },
    {
        "name": "LaCrosse Technology View LTV-R1, LTV-R3 Rainfall Gauge, LTV-W1/W2 Wind Sensor",
        "file": "lacrosse_r1.c",
        "modulation": "FSK",
        "short_pulse": 104,
        "long_pulse": 104,
        "gap": 9600,
    },
    {
        "name": "Apator Metra E-RM 30 water meter",
        "file": "apator_metra_erm30.c",
        "modulation": "FSK",
        "short_pulse": 25,
        "long_pulse": 25,
        "gap": 5000,
    },
    {
        "name": "CurrentCost Current Sensor",
        "file": "current_cost.c",
        "modulation": "FSK",
        "short_pulse": 250,
        "long_pulse": 250,
        "gap": 8000,
    },
    {
        "name": "Risco 2 Way Agility protocol, Risco PIR/PET Sensor RWX95P",
        "file": "risco_agility.c",
        "modulation": "OOK/ASK",
        "short_pulse": 175,
        "long_pulse": 175,
        "gap": 1000,
    },
    {
        "name": "LaCrosse Technology View LTV-WSDTH01 Breeze Pro Wind Sensor",
        "file": "lacrosse_breezepro.c",
        "modulation": "FSK",
        "short_pulse": 107,
        "long_pulse": 107,
        "gap": 5900,
    },
    {
        "name": "Vevor Wireless Weather Station 7-in-1",
        "file": "vevor_7in1.c",
        "modulation": "FSK",
        "short_pulse": 87,
        "long_pulse": 87,
        "gap": 9000,
    },
    {
        "name": "Maverick XR-30 BBQ Sensor",
        "file": "maverick_xr30.c",
        "modulation": "FSK",
        "short_pulse": 360,
        "long_pulse": 360,
        "gap": 4096,
    },
    {
        "name": "Maverick ET73",
        "file": "maverick_et73.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1050,
        "long_pulse": 2050,
        "gap": 2200,
    },
    {
        "name": "Oregon Scientific Weather Sensor",
        "file": "oregon_scientific.c",
        "modulation": "OOK/ASK",
        "short_pulse": 440,
        "long_pulse": 0,
        "gap": 2400,
    },
    {
        "name": "Interlogix GE UTC Security Devices",
        "file": "interlogix.c",
        "modulation": "OOK/ASK",
        "short_pulse": 122,
        "long_pulse": 244,
        "gap": 500,
    },
    {
        "name": "CED7000 Shot Timer",
        "file": "ced7000.c",
        "modulation": "FSK",
        "short_pulse": 1300,
        "long_pulse": 1300,
        "gap": 3500,
    },
    {
        "name": "Lock",
        "file": "astrostart_2000.c",
        "modulation": "OOK/ASK",
        "short_pulse": 326,
        "long_pulse": 526,
        "gap": 541,
    },
    {
        "name": "WG-PB12V1 Temperature Sensor",
        "file": "wg_pb12v1.c",
        "modulation": "OOK/ASK",
        "short_pulse": 564,
        "long_pulse": 1476,
        "gap": 2500,
    },
    {
        "name": "WallarGe CLTX001 Outdoor Temperature Sensor",
        "file": "wallarge_cltx001.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": 500,
        "gap": 650,
    },
    {
        "name": "ThermoPro TP862b TempSpike XR Wireless Dual-Probe Meat Thermometer",
        "file": "thermopro_tp862b.c",
        "modulation": "FSK",
        "short_pulse": 104,
        "long_pulse": 104,
        "gap": 2000,
    },
    {
        "name": "Govee Water Leak Detector H5059",
        "file": "govee_h5059.c",
        "modulation": "FSK",
        "short_pulse": 100,
        "long_pulse": 100,
        "gap": 2000,
    },
    {
        "name": "Intertechno 433",
        "file": "intertechno.c",
        "modulation": "OOK/ASK",
        "short_pulse": 330,
        "long_pulse": 1400,
        "gap": 1700,
    },
    {
        "name": "Audiovox PRO-OE3B Car Remote (-f 303.4M)",
        "file": "audiovox_pro_oe3b.c",
        "modulation": "OOK/ASK",
        "short_pulse": 445,
        "long_pulse": 895,
        "gap": 1790,
    },
    {
        "name": "LaCrosse WS-2310 / WS-3600 Weather Station",
        "file": "lacrossews.c",
        "modulation": "OOK/ASK",
        "short_pulse": 368,
        "long_pulse": 1464,
        "gap": 8000,
    },
    {
        "name": "LaCrosse TX141-Bv2, TX141TH-Bv2, TX141-Bv3, TX141W, TX145wsdth, (TFA, ORIA) sensor",
        "file": "lacrosse_tx141x.c",
        "modulation": "OOK/ASK",
        "short_pulse": 208,
        "long_pulse": 417,
        "gap": 833,
    },
    {
        "name": "Oil Ultrasonic SMART FSK",
        "file": "oil_smart.c",
        "modulation": "FSK",
        "short_pulse": 500,
        "long_pulse": 500,
        "gap": 2000,
    },
    {
        "name": "Voltcraft EnergyCount 3000 (ec3k)",
        "file": "ec3k.c",
        "modulation": "FSK",
        "short_pulse": 50,
        "long_pulse": 50,
        "gap": 3000,
    },
    {
        "name": "Geevon TX19-1 outdoor sensor",
        "file": "geevon_tx19.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": 500,
        "gap": 750,
    },
    {
        "name": "Nexus, FreeTec NC-7345, NX-3980, Solight TE82S, TFA 30.3209 temperature/humidity sensor",
        "file": "nexus.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1000,
        "long_pulse": 2000,
        "gap": 3000,
    },
    {
        "name": "Oil Ultrasonic STANDARD FSK",
        "file": "oil_standard.c",
        "modulation": "FSK",
        "short_pulse": 500,
        "long_pulse": 500,
        "gap": 2000,
    },
    {
        "name": "ThermoPro TP28b Super Long Range Wireless Meat Thermometer for Smoker BBQ Grill",
        "file": "thermopro_tp28b.c",
        "modulation": "FSK",
        "short_pulse": 105,
        "long_pulse": 105,
        "gap": 5500,
    },
    {
        "name": "Akhan 100F14 remote keyless entry",
        "file": "akhan_100F14.c",
        "modulation": "OOK/ASK",
        "short_pulse": 316,
        "long_pulse": 1020,
        "gap": 1800,
    },
    {
        "name": "LaCrosse Technology View LTV-WR1 Multi Sensor",
        "file": "lacrosse_wr1.c",
        "modulation": "FSK",
        "short_pulse": 104,
        "long_pulse": 104,
        "gap": 9600,
    },
    {
        "name": "ThermoPro TX-7B Outdoor Thermometer Hygrometer",
        "file": "thermopro_tx7b.c",
        "modulation": "FSK",
        "short_pulse": 108,
        "long_pulse": 108,
        "gap": 1500,
    },
    {
        "name": "Sainlogic SA8, Gevanti SA8 Weather Station",
        "file": "sainlogic_sa8.c",
        "modulation": "OOK/ASK",
        "short_pulse": 200,
        "long_pulse": 200,
        "gap": 2500,
    },
    {
        "name": "Globaltronics GT-WT-03 Sensor",
        "file": "gt_wt_03.c",
        "modulation": "OOK/ASK",
        "short_pulse": 256,
        "long_pulse": 625,
        "gap": 855,
    },
    {
        "name": "Cotech 36-7959, SwitchDocLabs FT020T wireless weather station with USB",
        "file": "cotech_36_7959.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 0,
        "gap": 1200,
    },
    {
        "name": "Rubicson 48659 Thermometer",
        "file": "rubicson_48659.c",
        "modulation": "OOK/ASK",
        "short_pulse": 940,
        "long_pulse": 1900,
        "gap": 2000,
    },
    {
        "name": "Bresser Thermo-/Hygro-Sensor 3CH",
        "file": "bresser_3ch.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": 500,
        "gap": 750,
    },
    {
        "name": "LightwaveRF",
        "file": "lightwave_rf.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": 1250,
        "gap": 1500,
    },
    {
        "name": "Danfoss CFR Thermostat",
        "file": "danfoss.c",
        "modulation": "FSK",
        "short_pulse": 100,
        "long_pulse": 100,
        "gap": 500,
    },
    {
        "name": "Efergy Optical",
        "file": "efergy_optical.c",
        "modulation": "FSK",
        "short_pulse": 64,
        "long_pulse": 136,
        "gap": 500,
    },
    {
        "name": "Springfield Temperature and Soil Moisture",
        "file": "springfield.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 5000,
    },
    {
        "name": "Ambient Weather TX-8300 Temperature/Humidity Sensor",
        "file": "ambientweather_tx8300.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 6500,
    },
    {
        "name": "TBH weather sensor",
        "file": "archos_tbh.c",
        "modulation": "FSK",
        "short_pulse": 212,
        "long_pulse": 212,
        "gap": 3000,
    },
    {
        "name": "Cardin S466-TX2",
        "file": "cardin.c",
        "modulation": "OOK/ASK",
        "short_pulse": 730,
        "long_pulse": 1400,
        "gap": 6150,
    },
    {
        "name": "Geevon TX16-3 outdoor sensor",
        "file": "geevon.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": 500,
        "gap": 750,
    },
    {
        "name": "X10 RF",
        "file": "x10_rf.c",
        "modulation": "OOK/ASK",
        "short_pulse": 562,
        "long_pulse": 1687,
        "gap": 2200,
    },
    {
        "name": "Orion Endpoint from Badger Meter, GIF2014W-OSE, water meter, hopping from 904.4 Mhz to 924.6Mhz (-s 1600k)",
        "file": "badger_orion_endpoint.c",
        "modulation": "FSK",
        "short_pulse": 10,
        "long_pulse": 10,
        "gap": 1000,
    },
    {
        "name": "Bresser lightning",
        "file": "bresser_lightning.c",
        "modulation": "FSK",
        "short_pulse": 124,
        "long_pulse": 124,
        "gap": 25000,
    },
    {
        "name": "Multiple",
        "file": "code_alarm_car_remote.c",
        "modulation": "OOK/ASK",
        "short_pulse": 550,
        "long_pulse": 1100,
        "gap": 1600,
    },
    {
        "name": "Flowis flow meters",
        "file": "flowis.c",
        "modulation": "FSK",
        "short_pulse": 10,
        "long_pulse": 10,
        "gap": 5000,
    },
    {
        "name": "Globaltronics GT-WT-02 Sensor",
        "file": "gt_wt_02.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2500,
        "long_pulse": 5000,
        "gap": 8000,
    },
    {
        "name": "Watchman Sonic Advanced / Plus, Tekelek",
        "file": "oil_watchman_advanced.c",
        "modulation": "FSK",
        "short_pulse": 500,
        "long_pulse": 500,
        "gap": 12500,
    },
    {
        "name": "Fine Offset Electronics WS90 weather station",
        "file": "fineoffset_ws90.c",
        "modulation": "FSK",
        "short_pulse": 58,
        "long_pulse": 58,
        "gap": 3000,
    },
    {
        "name": "ThermoPro TP211B Thermometer",
        "file": "thermopro_tp211b.c",
        "modulation": "FSK",
        "short_pulse": 105,
        "long_pulse": 105,
        "gap": 1500,
    },
    {
        "name": "Jansite TPMS Model Solar",
        "file": "tpms_jansite_solar.c",
        "modulation": "FSK",
        "short_pulse": 51,
        "long_pulse": 51,
        "gap": 5000,
    },
    {
        "name": "KlikAanKlikUit Wireless Switch",
        "file": "newkaku.c",
        "modulation": "OOK/ASK",
        "short_pulse": 300,
        "long_pulse": 1400,
        "gap": 2650,
    },
    {
        "name": "Baldr E0666TH Thermo-Hygrometer",
        "file": "baldr_therm.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1000,
        "long_pulse": 2000,
        "gap": 3000,
    },
    {
        "name": "EcoDHOME Smart Socket and MCEE Solar monitor",
        "file": "ecodhome.c",
        "modulation": "FSK",
        "short_pulse": 250,
        "long_pulse": 250,
        "gap": 6000,
    },
    {
        "name": "ERT Interval Data Message (IDM)",
        "file": "ert_idm.c",
        "modulation": "OOK/ASK",
        "short_pulse": 30,
        "long_pulse": 0,
        "gap": 20000,
    },
    {
        "name": "Inovalley kw9015b, TFA Dostmann 30.3161 (Rain and temperature sensor)",
        "file": "inovalley-kw9015b.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 4800,
    },
    {
        "name": "IBIS beacon",
        "file": "ibis_beacon.c",
        "modulation": "OOK/ASK",
        "short_pulse": 30,
        "long_pulse": 0,
        "gap": 100,
    },
    {
        "name": "Honeywell Door/Window Sensor, 2Gig DW10/DW11, RE208 repeater",
        "file": "honeywell.c",
        "modulation": "OOK/ASK",
        "short_pulse": 156,
        "long_pulse": 0,
        "gap": 292,
    },
    {
        "name": "Schrader TPMS",
        "file": "schraeder.c",
        "modulation": "OOK/ASK",
        "short_pulse": 120,
        "long_pulse": 0,
        "gap": 480,
    },
    {
        "name": "Ford Car Key",
        "file": "fordremote.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": 500,
        "gap": 4000,
    },
    {
        "name": "Solight TE44/TE66, EMOS E0107T, NX-6876-917",
        "file": "solight_te44.c",
        "modulation": "OOK/ASK",
        "short_pulse": 972,
        "long_pulse": 1932,
        "gap": 3000,
    },
    {
        "name": "TyreGuard 400 TPMS",
        "file": "tpms_tyreguard400.c",
        "modulation": "OOK/ASK",
        "short_pulse": 100,
        "long_pulse": 100,
        "gap": 0,
    },
    {
        "name": "Missil ML0757 weather station",
        "file": "missil_ml0757.c",
        "modulation": "OOK/ASK",
        "short_pulse": 975,
        "long_pulse": 1950,
        "gap": 2500,
    },
    {
        "name": "Efergy e2 classic",
        "file": "efergy_e2_classic.c",
        "modulation": "FSK",
        "short_pulse": 64,
        "long_pulse": 136,
        "gap": 500,
    },
    {
        "name": "Maverick ET-732/733 BBQ Sensor",
        "file": "maverick_et73x.c",
        "modulation": "OOK/ASK",
        "short_pulse": 230,
        "long_pulse": 0,
        "gap": 4000,
    },
    {
        "name": "TFA Dostmann 30.3221.02 T/H Outdoor Sensor (also 30.3249.02)",
        "file": "tfa_30_3221.c",
        "modulation": "OOK/ASK",
        "short_pulse": 235,
        "long_pulse": 480,
        "gap": 850,
    },
    {
        "name": "Porsche Boxster/Cayman TPMS",
        "file": "tpms_porsche.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "Jasco/GE Choice Alert Security Devices",
        "file": "jasco.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": 250,
        "gap": 1800,
    },
    {
        "name": "BMW Gen2 and Gen3 TPMS",
        "file": "tpms_bmw_g3.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 160,
    },
    {
        "name": "Rosstech Digital Control Unit DCU-706/Sundance/Jacuzzi",
        "file": "rosstech_dcu706.c",
        "modulation": "OOK/ASK",
        "short_pulse": 200,
        "long_pulse": 200,
        "gap": 2000,
    },
    {
        "name": "Homelead HG9901 (Geevon, Dr.Meter, Royal Gardineer) soil moisture/temp/light level sensor",
        "file": "homelead_hg9901.c",
        "modulation": "OOK/ASK",
        "short_pulse": 432,
        "long_pulse": 1228,
        "gap": 2000,
    },
    {
        "name": "Renault TPMS",
        "file": "tpms_renault.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "Emax W6, rebrand Altronics x7063/4/x7064A, Optex 990040/50/51, Orium 13093/13123, Infactory FWS-1200, Newentor Q9, Otio 810025, Protmex PT3390A, Jula Marquant 014331/32, TechniSat IMETEO X6 76-4924-00, Weather Station or temperature/humidity sensor",
        "file": "emax.c",
        "modulation": "FSK",
        "short_pulse": 90,
        "long_pulse": 90,
        "gap": 9000,
    },
    {
        "name": "GM ABO1502T Car Remote (-f 314.9M)",
        "file": "gm_car_remote.c",
        "modulation": "OOK/ASK",
        "short_pulse": 300,
        "long_pulse": 500,
        "gap": 20000,
    },
    {
        "name": "Toyota TPMS",
        "file": "tpms_toyota.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "Continental KR5V2X Car Remote (-f 313.8M -s 1024k)",
        "file": "continental_car_remote.c",
        "modulation": "FSK",
        "short_pulse": 100,
        "long_pulse": 200,
        "gap": 1500,
    },
    {
        "name": "Kedsum Temperature & Humidity Sensor, Pearl NC-7415",
        "file": "kedsum.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 4400,
    },
    {
        "name": "Arexx Multilogger IP-HA90, IP-TH78EXT, TSN-70E",
        "file": "arexx_ml.c",
        "modulation": "FSK",
        "short_pulse": 208,
        "long_pulse": 208,
        "gap": 450,
    },
    {
        "name": "TFA Marbella Pool Thermometer",
        "file": "tfa_marbella.c",
        "modulation": "FSK",
        "short_pulse": 105,
        "long_pulse": 105,
        "gap": 2000,
    },
    {
        "name": "Revolt NC-5642 Energy Meter",
        "file": "revolt_nc5462.c",
        "modulation": "OOK/ASK",
        "short_pulse": 200,
        "long_pulse": 320,
        "gap": 10024,
    },
    {
        "name": "Linear Megacode Garage/Gate Remotes",
        "file": "megacode.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1000,
        "long_pulse": 1000,
        "gap": 9000,
    },
    {
        "name": "ERT Standard Consumption Message (SCM)",
        "file": "ert_scm.c",
        "modulation": "OOK/ASK",
        "short_pulse": 30,
        "long_pulse": 0,
        "gap": 0,
    },
    {
        "name": "Generic temperature sensor 1",
        "file": "generic_temperature_sensor.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 4800,
    },
    {
        "name": "Generic Remote SC226x EV1527",
        "file": "generic_remote.c",
        "modulation": "OOK/ASK",
        "short_pulse": 464,
        "long_pulse": 1404,
        "gap": 1800,
    },
    {
        "name": "GE Color Effects",
        "file": "ge_coloreffects.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 450,
    },
    {
        "name": "Security+ 2.0 (Keyfob)",
        "file": "secplus_v2.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": 250,
        "gap": 1500,
    },
    {
        "name": "Nice Flor-s remote control for gates",
        "file": "nice_flor_s.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 1000,
        "gap": 1500,
    },
    {
        "name": "Companion WTR001 Temperature Sensor",
        "file": "companion_wtr001.c",
        "modulation": "OOK/ASK",
        "short_pulse": 732,
        "long_pulse": 2196,
        "gap": 4000,
    },
    {
        "name": "TFA Drop Rain Gauge 30.3233.01",
        "file": "tfa_drop_30.3233.c",
        "modulation": "OOK/ASK",
        "short_pulse": 255,
        "long_pulse": 510,
        "gap": 1300,
    },
    {
        "name": "Siemens 5WY72XX Car Remote (-f 315.1M)",
        "file": "siemens_5wy72xx.c",
        "modulation": "OOK/ASK",
        "short_pulse": 220,
        "long_pulse": None,
        "gap": 10000,
    },
    {
        "name": "Elantra2012 TPMS",
        "file": "tpms_elantra2012.c",
        "modulation": "FSK",
        "short_pulse": 49,
        "long_pulse": 49,
        "gap": 200,
    },
    {
        "name": "Chuango Security Technology",
        "file": "chuango.c",
        "modulation": "OOK/ASK",
        "short_pulse": 568,
        "long_pulse": 1704,
        "gap": 1800,
    },
    {
        "name": "CRC-16/CMS",
        "file": "rojaflex.c",
        "modulation": "FSK",
        "short_pulse": 100,
        "long_pulse": 100,
        "gap": 102400,
    },
    {
        "name": "Norgo NGE101",
        "file": "norgo.c",
        "modulation": "OOK/ASK",
        "short_pulse": 486,
        "long_pulse": 972,
        "gap": 2100,
    },
    {
        "name": "Rubicson, TFA 30.3197 or InFactory PT-310 Temperature Sensor",
        "file": "rubicson.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1000,
        "long_pulse": 2000,
        "gap": 3000,
    },
    {
        "name": "Bresser Thermo-/Hygro-Sensor Explore Scientific ST1005H",
        "file": "bresser_st1005h.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2500,
        "long_pulse": 4500,
        "gap": 4500,
    },
    {
        "name": "RFM69 LowPowerLab Moteino board (-s 1000k)",
        "file": "rfm69_lowpowerlab_moteino.c",
        "modulation": "FSK",
        "short_pulse": 18,
        "long_pulse": 18,
        "gap": 400,
    },
    {
        "name": "TRW TPMS OOK OEM and Clone models",
        "file": "tpms_trw.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "PMV-107J (Toyota) TPMS",
        "file": "tpms_pmv107j.c",
        "modulation": "FSK",
        "short_pulse": 100,
        "long_pulse": 100,
        "gap": 250,
    },
    {
        "name": "Badger ORION water meter, 100kbps (-f 916.45M -s 1200k)",
        "file": "badger_water.c",
        "modulation": "FSK",
        "short_pulse": 10,
        "long_pulse": 10,
        "gap": 1000,
    },
    {
        "name": "Steelmate TPMS",
        "file": "steelmate.c",
        "modulation": "FSK",
        "short_pulse": 50,
        "long_pulse": 50,
        "gap": 120,
    },
    {
        "name": "Proove / Nexa / KlikAanKlikUit Wireless Switch",
        "file": "proove.c",
        "modulation": "OOK/ASK",
        "short_pulse": 270,
        "long_pulse": 1300,
        "gap": 2650,
    },
    {
        "name": "Quinetic",
        "file": "quinetic.c",
        "modulation": "FSK",
        "short_pulse": 10,
        "long_pulse": 10,
        "gap": 120,
    },
    {
        "name": "Auriol AFW2A1 temperature/humidity sensor",
        "file": "auriol_afw2a1.c",
        "modulation": "OOK/ASK",
        "short_pulse": 576,
        "long_pulse": 1536,
        "gap": 0,
    },
    {
        "name": "Mueller Hot Rod water meter",
        "file": "mueller_hotrod.c",
        "modulation": "FSK",
        "short_pulse": 26,
        "long_pulse": 26,
        "gap": 2500,
    },
    {
        "name": "Opus/Imagintronix XT300 Soil Moisture",
        "file": "opus_xt300.c",
        "modulation": "OOK/ASK",
        "short_pulse": 544,
        "long_pulse": 932,
        "gap": 10000,
    },
    {
        "name": "Hyundai TPMS (VDO)",
        "file": "tpms_hyundai_vdo.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "ThermoPro TX-2C Thermometer and Humidity sensor",
        "file": "thermopro_tx2c.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1958,
        "long_pulse": 3825,
        "gap": 3829,
    },
    {
        "name": "Unbranded SolarTPMS for trucks",
        "file": "tpms_truck.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "Rubicson Pool Thermometer 48942",
        "file": "rubicson_pool_48942.c",
        "modulation": "OOK/ASK",
        "short_pulse": 280,
        "long_pulse": 480,
        "gap": 6000,
    },
    {
        "name": "Bresser Weather Center 5-in-1",
        "file": "bresser_5in1.c",
        "modulation": "FSK",
        "short_pulse": 124,
        "long_pulse": 124,
        "gap": 25000,
    },
    {
        "name": "DeltaDore X3D devices",
        "file": "deltadore_x3d.c",
        "modulation": "FSK",
        "short_pulse": 25,
        "long_pulse": 25,
        "gap": 800,
    },
    {
        "name": "Chrysler Car Remote (-f 315.1M -s 920k)",
        "file": "chrysler_car_remote.c",
        "modulation": "OOK/ASK",
        "short_pulse": 350,
        "long_pulse": 350,
        "gap": 350,
    },
    {
        "name": "Globaltronics QUIGG GT-TMBBQ-05",
        "file": "gt_tmbbq05.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 4200,
    },
    {
        "name": "Bresser Weather Center 6-in-1, 7-in-1 indoor, soil, new 5-in-1, 3-in-1 wind gauge, Froggit WH6000, Ventus C8488A",
        "file": "bresser_6in1.c",
        "modulation": "FSK",
        "short_pulse": 124,
        "long_pulse": 124,
        "gap": 25000,
    },
    {
        "name": "Wireless M-Bus, Mode C&T, 100kbps (-f 868.95M -s 1200k)",
        "file": "m_bus.c",
        "modulation": "FSK",
        "short_pulse": 10,
        "long_pulse": 10,
        "gap": 500,
    },
    {
        "name": "RainPoint soil temperature and moisture sensor",
        "file": "rainpoint.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 500,
        "gap": 1500,
    },
    {
        "name": "Gasmate BA1008 meat thermometer",
        "file": "gasmate_ba1008.c",
        "modulation": "OOK/ASK",
        "short_pulse": 536,
        "long_pulse": 1668,
        "gap": 2000,
    },
    {
        "name": "Silvercrest Remote Control",
        "file": "silvercrest.c",
        "modulation": "OOK/ASK",
        "short_pulse": 264,
        "long_pulse": 744,
        "gap": 12000,
    },
    {
        "name": "Ambient Weather WH31L (FineOffset WH57) Lightning-Strike sensor",
        "file": "fineoffset_wh31l.c",
        "modulation": "FSK",
        "short_pulse": 56,
        "long_pulse": 56,
        "gap": 1000,
    },
    {
        "name": "TFA Dostmann 14.1504.V2 Radio-controlled grill and meat thermometer",
        "file": "tfa_14_1504_v2.c",
        "modulation": "FSK",
        "short_pulse": 360,
        "long_pulse": 360,
        "gap": 4096,
    },
    {
        "name": "Insteon",
        "file": "insteon.c",
        "modulation": "FSK",
        "short_pulse": 110,
        "long_pulse": 110,
        "gap": 500,
    },
    {
        "name": "LaCrosse/ELV/Conrad WS7000/WS2500 weather sensors",
        "file": "lacrosse_ws7000.c",
        "modulation": "OOK/ASK",
        "short_pulse": 400,
        "long_pulse": 800,
        "gap": 1100,
    },
    {
        "name": "Fine Offset / Ecowitt WH55 water leak sensor",
        "file": "fineoffset_wh55.c",
        "modulation": "FSK",
        "short_pulse": 60,
        "long_pulse": 60,
        "gap": 2500,
    },
    {
        "name": "Vaillant calorMatic VRT340f Central Heating Control",
        "file": "vaillant_vrt340f.c",
        "modulation": "OOK/ASK",
        "short_pulse": 836,
        "long_pulse": 1648,
        "gap": 4000,
    },
    {
        "name": "MIC 6SC2 Car Remote (-f 315.1M)",
        "file": "mic6sc2_car_remote.c",
        "modulation": "OOK/ASK",
        "short_pulse": 250,
        "long_pulse": None,
        "gap": 10000,
    },
    {
        "name": "Ambient Weather WH31E Thermo-Hygrometer Sensor, EcoWitt WH40 rain gauge, WS68 weather station",
        "file": "ambientweather_wh31e.c",
        "modulation": "FSK",
        "short_pulse": 56,
        "long_pulse": 56,
        "gap": 1500,
    },
    {
        "name": "WS2032 weather station",
        "file": "ws2032.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 1000,
        "gap": 750,
    },
    {
        "name": "Fine Offset Electronics WS80 weather station",
        "file": "fineoffset_ws80.c",
        "modulation": "FSK",
        "short_pulse": 58,
        "long_pulse": 58,
        "gap": 1500,
    },
    {
        "name": "TFA-Twin-Plus-30.3049, Conrad KW9010, Ea2 BL999",
        "file": "tfa_twin_plus_30.3049.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 6000,
    },
    {
        "name": "Kerui PIR / Contact Sensor",
        "file": "kerui.c",
        "modulation": "OOK/ASK",
        "short_pulse": 420,
        "long_pulse": 960,
        "gap": 1100,
    },
    {
        "name": "SRSmith Pool Light Remote Control SRS-2C-TX (-f 915M)",
        "file": "srsmith_pool_srs_2c_tx.c",
        "modulation": "FSK",
        "short_pulse": 100,
        "long_pulse": 100,
        "gap": 4096,
    },
    {
        "name": "HIDEKI TS04 Temperature, Humidity, Wind and Rain Sensor",
        "file": "hideki.c",
        "modulation": "OOK/ASK",
        "short_pulse": 520,
        "long_pulse": 1040,
        "gap": 4000,
    },
    {
        "name": "Acurite 896 Rain Gauge",
        "file": "acurite.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1000,
        "long_pulse": 2000,
        "gap": 3500,
    },
    {
        "name": "Ambient Weather F007TH, TFA 30.3208.02, SwitchDocLabs F016TH temperature sensor",
        "file": "ambient_weather.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 0,
        "gap": 2400,
    },
    {
        "name": "Apator Metra E-ITN 30 heat cost allocator",
        "file": "apator_metra_eitn30.c",
        "modulation": "FSK",
        "short_pulse": 25,
        "long_pulse": 25,
        "gap": 5000,
    },
    {
        "name": "ThermoPro Meat Thermometers, TP828B 2 probes with Temp, BBQ Target LO and HI",
        "file": "thermopro_tp82xb.c",
        "modulation": "FSK",
        "short_pulse": 102,
        "long_pulse": 102,
        "gap": 1500,
    },
    {
        "name": "Fine Offset Electronics WH43 air quality sensor",
        "file": "fineoffset_wh43.c",
        "modulation": "FSK",
        "short_pulse": 58,
        "long_pulse": 58,
        "gap": 2500,
    },
    {
        "name": "Honda Car Key",
        "file": "hondaremote.c",
        "modulation": "FSK",
        "short_pulse": 250,
        "long_pulse": 500,
        "gap": 2000,
    },
    {
        "name": "FS20 / FHT",
        "file": "fs20.c",
        "modulation": "OOK/ASK",
        "short_pulse": 400,
        "long_pulse": 600,
        "gap": 9000,
    },
    {
        "name": "ThermoPro TP08/TP12/TP20 thermometer",
        "file": "thermopro_tp12.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 1500,
        "gap": 2000,
    },
    {
        "name": "Thermor DG950 weather station",
        "file": "thermor.c",
        "modulation": "OOK/ASK",
        "short_pulse": 680,
        "long_pulse": 2100,
        "gap": 1438,
    },
    {
        "name": "Revolt ZX-7717 power meter",
        "file": "revolt_zx7717.c",
        "modulation": "OOK/ASK",
        "short_pulse": 310,
        "long_pulse": 310,
        "gap": 900,
    },
    {
        "name": "Lock",
        "file": "compustar_1wg3r.c",
        "modulation": "OOK/ASK",
        "short_pulse": 708,
        "long_pulse": 1076,
        "gap": 1532,
    },
    {
        "name": "SmartFire Proflame 2 remote control",
        "file": "proflame2.c",
        "modulation": "OOK/ASK",
        "short_pulse": 417,
        "long_pulse": 417,
        "gap": 1000,
    },
    {
        "name": "Govee Water Leak Detector H5054, Door Contact Sensor B5023",
        "file": "govee.c",
        "modulation": "OOK/ASK",
        "short_pulse": 440,
        "long_pulse": 940,
        "gap": 900,
    },
    {
        "name": "SimpliSafe Home Security System (May require disabling automatic gain for KeyPad decodes)",
        "file": "simplisafe.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 1000,
        "gap": 2200,
    },
    {
        "name": "ESIC EMT7110 power meter",
        "file": "esic_emt7110.c",
        "modulation": "FSK",
        "short_pulse": 104,
        "long_pulse": 104,
        "gap": 10000,
    },
    {
        "name": "Somfy io-homecontrol",
        "file": "somfy_iohc.c",
        "modulation": "FSK",
        "short_pulse": 26,
        "long_pulse": 26,
        "gap": 300,
    },
    {
        "name": "Watchman Sonic / Apollo Ultrasonic / Beckett Rocket oil tank monitor",
        "file": "oil_watchman.c",
        "modulation": "FSK",
        "short_pulse": 1000,
        "long_pulse": 1000,
        "gap": 4000,
    },
    {
        "name": "AlectoV1 Weather Sensor (Alecto WS3500 WS4500 Ventus W155/W044 Oregon)",
        "file": "alecto.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 7000,
    },
    {
        "name": "EezTire E618, Carchet TPMS, TST-507 TPMS",
        "file": "tpms_eezrv.c",
        "modulation": "OOK/ASK",
        "short_pulse": 50,
        "long_pulse": 50,
        "gap": 120,
    },
    {
        "name": "Oria WA150KM freezer and fridge thermometer",
        "file": "oria_wa150km.c",
        "modulation": "OOK/ASK",
        "short_pulse": 490,
        "long_pulse": 490,
        "gap": 1500,
    },
    {
        "name": "Kia TPMS (-s 1000k)",
        "file": "tpms_kia.c",
        "modulation": "FSK",
        "short_pulse": 50,
        "long_pulse": 50,
        "gap": 200,
    },
    {
        "name": "ELV EM 1000",
        "file": "elv.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 1000,
        "gap": 7250,
    },
    {
        "name": "Fine Offset Electronics, WH2, WH5, Telldus Temperature/Humidity/Rain Sensor",
        "file": "fineoffset.c",
        "modulation": "FSK",
        "short_pulse": 500,
        "long_pulse": 1500,
        "gap": 1200,
    },
    {
        "name": "TFA pool temperature sensor",
        "file": "tfa_pool_thermometer.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4600,
        "gap": 7800,
    },
    {
        "name": "Schou 72543 Day Rain Gauge, Motonet MTX Rain, MarQuant Rain Gauge, TFA Dostmann 30.3252.01/47.3006.01 Rain Gauge and Thermometer, ADE WS1907",
        "file": "schou_72543_rain.c",
        "modulation": "OOK/ASK",
        "short_pulse": 972,
        "long_pulse": 2680,
        "gap": 7328,
    },
    {
        "name": "Nidec Car Remote (-f 313.8M -s 1024k)",
        "file": "nidec_car_remote.c",
        "modulation": "FSK",
        "short_pulse": 250,
        "long_pulse": 500,
        "gap": 1000,
    },
    {
        "name": "Thermopro TP11 Thermometer",
        "file": "thermopro_tp11.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 1500,
        "gap": 2000,
    },
    {
        "name": "Celsia CZC1 Thermostat",
        "file": "celsia_czc1.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1220,
        "long_pulse": 1220,
        "gap": 4880,
    },
    {
        "name": "Generic wireless motion sensor",
        "file": "generic_motion.c",
        "modulation": "OOK/ASK",
        "short_pulse": 888,
        "long_pulse": None,
        "gap": 1784,
    },
    {
        "name": "WT0124 Pool Thermometer",
        "file": "wt0124.c",
        "modulation": "OOK/ASK",
        "short_pulse": 680,
        "long_pulse": 1850,
        "gap": 30000,
    },
    {
        "name": "TS-FT002 Wireless Ultrasonic Tank Liquid Level Meter With Temperature Sensor",
        "file": "ts_ft002.c",
        "modulation": "OOK/ASK",
        "short_pulse": 464,
        "long_pulse": 948,
        "gap": 1200,
    },
    {
        "name": "RainPoint HCS012ARF Rain Gauge sensor",
        "file": "rainpoint_hcs012arf.c",
        "modulation": "OOK/ASK",
        "short_pulse": 320,
        "long_pulse": 320,
        "gap": 1000,
    },
    {
        "name": "DirecTV RC66RX Remote Control",
        "file": "directv.c",
        "modulation": "FSK",
        "short_pulse": 600,
        "long_pulse": 600,
        "gap": 30000,
    },
    {
        "name": "Jansite TPMS Model TY02S",
        "file": "tpms_jansite.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "Somfy RTS",
        "file": "somfy_rts.c",
        "modulation": "OOK/ASK",
        "short_pulse": 604,
        "long_pulse": 604,
        "gap": 2416,
    },
    {
        "name": "LaCrosse TX31U-IT, The Weather Channel WS-1910TWC-IT",
        "file": "lacrosse_tx31u.c",
        "modulation": "FSK",
        "short_pulse": 116,
        "long_pulse": 116,
        "gap": 20000,
    },
    {
        "name": "Chamberlain CWPIRC PIR Sensor",
        "file": "chamberlain_cwpirc.c",
        "modulation": "FSK",
        "short_pulse": 25,
        "long_pulse": 25,
        "gap": 500,
    },
    {
        "name": "Renault 0435R TPMS",
        "file": "tpms_renault_0435r.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "RF-tech",
        "file": "rftech.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 5000,
    },
    {
        "name": "Brennenstuhl RCS 2044",
        "file": "brennenstuhl_rcs_2044.c",
        "modulation": "OOK/ASK",
        "short_pulse": 320,
        "long_pulse": 968,
        "gap": 1500,
    },
    {
        "name": "Emos TTX201 Temperature Sensor",
        "file": "ttx201.c",
        "modulation": "OOK/ASK",
        "short_pulse": 510,
        "long_pulse": 0,
        "gap": 1700,
    },
    {
        "name": "Philips outdoor temperature sensor (type AJ7010)",
        "file": "philips_aj7010.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 6000,
        "gap": 1000,
    },
    {
        "name": "EnOcean ERP1",
        "file": "enocean_erp1.c",
        "modulation": "OOK/ASK",
        "short_pulse": 8,
        "long_pulse": 8,
        "gap": 0,
    },
    {
        "name": "inFactory, nor-tec, FreeTec NC-3982-913 temperature humidity sensor",
        "file": "infactory.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 500,
    },
    {
        "name": "BlueLine Innovations Power Cost Monitor",
        "file": "blueline.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 1000,
        "gap": 2000,
    },
    {
        "name": "WT450, WT260H, WT405H",
        "file": "wt450.c",
        "modulation": "OOK/ASK",
        "short_pulse": 976,
        "long_pulse": 1952,
        "gap": 18000,
    },
    {
        "name": "Auriol 4-LD5661/4-LD5972/4-LD6313 temperature/rain sensors",
        "file": "auriol_4ld5661.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1000,
        "long_pulse": 2000,
        "gap": 2500,
    },
    {
        "name": "Burnhard BBQ thermometer",
        "file": "burnhardbbq.c",
        "modulation": "OOK/ASK",
        "short_pulse": 240,
        "long_pulse": 484,
        "gap": 840,
    },
    {
        "name": "Amazon Basics Meat Thermometer",
        "file": "abmt.c",
        "modulation": "OOK/ASK",
        "short_pulse": 550,
        "long_pulse": 550,
        "gap": 2000,
    },
    {
        "name": "EMOS E6016 rain gauge",
        "file": "emos_e6016_rain.c",
        "modulation": "OOK/ASK",
        "short_pulse": 300,
        "long_pulse": 800,
        "gap": 1000,
    },
    {
        "name": "Yale HSA (Home Security Alarm), YES-Alarmkit",
        "file": "yale_hsa.c",
        "modulation": "OOK/ASK",
        "short_pulse": 850,
        "long_pulse": 1460,
        "gap": 5380,
    },
    {
        "name": "Auriol AHFL temperature/humidity sensor",
        "file": "auriol_ahfl.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2100,
        "long_pulse": 4150,
        "gap": 0,
    },
    {
        "name": "Nissan TPMS",
        "file": "tpms_nissan.c",
        "modulation": "FSK",
        "short_pulse": 120,
        "long_pulse": 120,
        "gap": 250,
    },
    {
        "name": "Baldr / RainPoint rain gauge.",
        "file": "baldr_rain.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1000,
        "long_pulse": 2000,
        "gap": 3000,
    },
    {
        "name": "Inkbird ITH-20R temperature humidity sensor",
        "file": "inkbird_ith20r.c",
        "modulation": "FSK",
        "short_pulse": 100,
        "long_pulse": 100,
        "gap": 4000,
    },
    {
        "name": "ThermoPro-TX2 temperature sensor",
        "file": "thermopro_tx2.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 7000,
    },
    {
        "name": "Auriol AFT 77 B2 temperature sensor",
        "file": "auriol_aft77b2.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 920,
        "gap": 1104,
    },
    {
        "name": "BMW Gen4-Gen5 TPMS and Audi TPMS Pressure Alert, multi-brand HUF/Beru, Continental, Schrader/Sensata, Audi",
        "file": "tpms_bmw.c",
        "modulation": "FSK",
        "short_pulse": 25,
        "long_pulse": 25,
        "gap": 100,
    },
    {
        "name": "Sharp SPC775 weather station",
        "file": "sharp_spc775.c",
        "modulation": "FSK",
        "short_pulse": 225,
        "long_pulse": 425,
        "gap": 2900,
    },
    {
        "name": "Waveman Switch Transmitter",
        "file": "waveman.c",
        "modulation": "OOK/ASK",
        "short_pulse": 357,
        "long_pulse": 1064,
        "gap": 1400,
    },
    {
        "name": " --",
        "file": "honeywell_cm921.c",
        "modulation": "FSK",
        "short_pulse": 26,
        "long_pulse": 26,
        "gap": 0,
    },
    {
        "name": "Cavius smoke, heat and water detector",
        "file": "cavius.c",
        "modulation": "FSK",
        "short_pulse": 206,
        "long_pulse": 206,
        "gap": 2700,
    },
    {
        "name": "LaCrosse TX29IT, TFA Dostmann 30.3159.IT Temperature sensor",
        "file": "lacrosse_tx35.c",
        "modulation": "FSK",
        "short_pulse": 55,
        "long_pulse": 55,
        "gap": 4000,
    },
    {
        "name": "Oregon Scientific SL109H Remote Thermal Hygro Sensor",
        "file": "oregon_scientific_sl109h.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 5000,
    },
    {
        "name": "Markisol, E-Motion, BOFU, Rollerhouse, BF-30x, BF-415 curtain remote",
        "file": "markisol.c",
        "modulation": "OOK/ASK",
        "short_pulse": 368,
        "long_pulse": 704,
        "gap": 5628,
    },
    {
        "name": "WEC-2103 temperature/humidity sensor",
        "file": "wec2103.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1900,
        "long_pulse": 3800,
        "gap": 4400,
    },
    {
        "name": "bm5-v2 12V Battery Monitor",
        "file": "bm5.c",
        "modulation": "OOK/ASK",
        "short_pulse": 225,
        "long_pulse": 675,
        "gap": 6000,
    },
    {
        "name": "flex",
        "file": "flex.c",
        "modulation": "FSK",
        "short_pulse": None,
        "long_pulse": None,
        "gap": None,
    },
    {
        "name": "Universal (Reverseable) 24V Fan Controller",
        "file": "universalfanctrl.c",
        "modulation": "OOK/ASK",
        "short_pulse": 256,
        "long_pulse": 756,
        "gap": 8000,
    },
    {
        "name": "AOK Weather Station rebrand Holman Industries iWeather WS5029, Conrad AOK-5056, Optex 990018",
        "file": "holman_ws5029.c",
        "modulation": "FSK",
        "short_pulse": 100,
        "long_pulse": 100,
        "gap": 19200,
    },
    {
        "name": "Philips outdoor temperature sensor (type AJ3650)",
        "file": "philips_aj3650.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 6000,
        "gap": 8000,
    },
    {
        "name": "GM-Aftermarket TPMS",
        "file": "tpms_gm.c",
        "modulation": "OOK/ASK",
        "short_pulse": 120,
        "long_pulse": 0,
        "gap": 15600,
    },
    {
        "name": "Vauno EN8822C",
        "file": "vauno_en8822c.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 5000,
    },
    {
        "name": "Dish remote 6.3",
        "file": "dish_remote_6_3.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1692,
        "long_pulse": 2812,
        "gap": 4500,
    },
    {
        "name": "Template decoder",
        "file": "new_template.c",
        "modulation": "OOK/ASK",
        "short_pulse": 132,
        "long_pulse": 224,
        "gap": 300,
    },
    {
        "name": "Eurochron temperature and humidity sensor",
        "file": "eurochron.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1016,
        "long_pulse": 2024,
        "gap": 2100,
    },
    {
        "name": "Fine Offset Electronics WN34S/L/D and Froggit DP150/D35 temperature sensor",
        "file": "fineoffset_wn34.c",
        "modulation": "FSK",
        "short_pulse": 58,
        "long_pulse": 58,
        "gap": 2500,
    },
    {
        "name": "Fine Offset Electronics WS85 weather station",
        "file": "fineoffset_ws85.c",
        "modulation": "FSK",
        "short_pulse": 58,
        "long_pulse": 58,
        "gap": 3000,
    },
    {
        "name": "Citroen TPMS",
        "file": "tpms_citroen.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "Auriol HG02832, HG05124A-DCF, Rubicson 48957 temperature/humidity sensor",
        "file": "auriol_hg02832.c",
        "modulation": "OOK/ASK",
        "short_pulse": 252,
        "long_pulse": 612,
        "gap": 860,
    },
    {
        "name": "Standard Consumption Message Plus (SCMplus)",
        "file": "scmplus.c",
        "modulation": "OOK/ASK",
        "short_pulse": 30,
        "long_pulse": 0,
        "gap": 0,
    },
    {
        "name": "ESA1000 / ESA2000 Energy Monitor",
        "file": "esa.c",
        "modulation": "OOK/ASK",
        "short_pulse": 260,
        "long_pulse": 0,
        "gap": 3000,
    },
    {
        "name": "OSv1 Temperature Sensor",
        "file": "oregon_scientific_v1.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1465,
        "long_pulse": None,
        "gap": 5780,
    },
    {
        "name": "Landis & Gyr Gridstream Power Meters 9.6k",
        "file": "gridstream.c",
        "modulation": "FSK",
        "short_pulse": 104,
        "long_pulse": 104,
        "gap": 20000,
    },
    {
        "name": "Blyss DC5-UK-WH",
        "file": "blyss.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 1500,
        "gap": 2500,
    },
    {
        "name": "LaCrosse TX Temperature / Humidity Sensor",
        "file": "lacrosse.c",
        "modulation": "FSK",
        "short_pulse": 550,
        "long_pulse": 1400,
        "gap": 3000,
    },
    {
        "name": "EMOS E6016 weatherstation with DCF77",
        "file": "emos_e6016.c",
        "modulation": "OOK/ASK",
        "short_pulse": 280,
        "long_pulse": 796,
        "gap": 3000,
    },
    {
        "name": "Microchip HCS200/HCS300 KeeLoq Hopping Encoder based remotes",
        "file": "hcs200.c",
        "modulation": "FSK",
        "short_pulse": 370,
        "long_pulse": 772,
        "gap": 1500,
    },
    {
        "name": "Telldus weather station FT0385R sensors",
        "file": "telldus_ft0385r.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 0,
        "gap": 1200,
    },
    {
        "name": "Acurite Grill/Meat Thermometer 01185M",
        "file": "acurite_01185m.c",
        "modulation": "OOK/ASK",
        "short_pulse": 840,
        "long_pulse": 2070,
        "gap": 6600,
    },
    {
        "name": "TFA Dostmann 30.3196 T/H outdoor sensor",
        "file": "tfa_30_3196.c",
        "modulation": "FSK",
        "short_pulse": 245,
        "long_pulse": 0,
        "gap": 22000,
    },
    {
        "name": "Bresser Weather Center 7-in-1, Air Quality PM2.5/PM10 7009970, CO2 7009977, HCHO/VOC 7009978 sensors",
        "file": "bresser_7in1.c",
        "modulation": "FSK",
        "short_pulse": 124,
        "long_pulse": 124,
        "gap": 25000,
    },
    {
        "name": "X10 Security",
        "file": "x10_sec.c",
        "modulation": "OOK/ASK",
        "short_pulse": 562,
        "long_pulse": 1687,
        "gap": 2200,
    },
    {
        "name": "Funkbus / Instafunk (Berker, Gira, Jung)",
        "file": "funkbus.c",
        "modulation": "OOK/ASK",
        "short_pulse": 500,
        "long_pulse": 1000,
        "gap": 2000,
    },
    {
        "name": "Prologue, FreeTec NC-7104, NC-7159-675 temperature sensor",
        "file": "prologue.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 7000,
    },
    {
        "name": "Atech-WS308 temperature sensor",
        "file": "atech_ws308.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1600,
        "long_pulse": 1832,
        "gap": 2500,
    },
    {
        "name": "Conrad S3318P, FreeTec NC-5849-913 temperature humidity sensor, ORIA WA50 ST389 temperature sensor",
        "file": "s3318p.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1900,
        "long_pulse": 3800,
        "gap": 4400,
    },
    {
        "name": "LaCrosse TX34-IT rain gauge",
        "file": "lacrosse_tx34.c",
        "modulation": "FSK",
        "short_pulse": 58,
        "long_pulse": 58,
        "gap": 4000,
    },
    {
        "name": "HT680 Remote control",
        "file": "ht680.c",
        "modulation": "OOK/ASK",
        "short_pulse": 200,
        "long_pulse": 600,
        "gap": 1200,
    },
    {
        "name": "Quhwa",
        "file": "quhwa.c",
        "modulation": "OOK/ASK",
        "short_pulse": 360,
        "long_pulse": 1070,
        "gap": 6600,
    },
    {
        "name": "Regency Ceiling Fan Remote (-f 303.75M to 303.96M)",
        "file": "regency_fan.c",
        "modulation": "OOK/ASK",
        "short_pulse": 580,
        "long_pulse": 976,
        "gap": 8000,
    },
    {
        "name": "LaCrosse Technology View LTV-TH Thermo/Hygro Sensor",
        "file": "lacrosse_th3.c",
        "modulation": "FSK",
        "short_pulse": 104,
        "long_pulse": 104,
        "gap": 9600,
    },
    {
        "name": "FT-004-B Temperature Sensor",
        "file": "ft004b.c",
        "modulation": "OOK/ASK",
        "short_pulse": 1956,
        "long_pulse": 3900,
        "gap": 4000,
    },
    {
        "name": "Fine Offset Electronics WH45 air quality sensor",
        "file": "fineoffset_wh45.c",
        "modulation": "FSK",
        "short_pulse": 58,
        "long_pulse": 58,
        "gap": 2500,
    },
    {
        "name": "Ford TPMS",
        "file": "tpms_ford.c",
        "modulation": "FSK",
        "short_pulse": 52,
        "long_pulse": 52,
        "gap": 150,
    },
    {
        "name": "Esperanza EWS",
        "file": "esperanza_ews.c",
        "modulation": "OOK/ASK",
        "short_pulse": 2000,
        "long_pulse": 4000,
        "gap": 4400,
    },
    {
        "name": "Fine Offset Electronics WH1080/WH3080 Weather Station",
        "file": "fineoffset_wh1080.c",
        "modulation": "FSK",
        "short_pulse": 544,
        "long_pulse": 1524,
        "gap": 2800,
    },
]


def _within_tolerance(observed: float, expected: float, tolerance: float) -> bool:
    delta = abs(expected) * tolerance
    return (expected - delta) <= observed <= (expected + delta)


def _load_user_signatures() -> list[dict[str, Any]]:
    """Load user-captured signatures persisted on disk."""
    try:
        data = json.loads(USER_SIGNATURES_FILE.read_text(encoding="utf-8"))
    except Exception:
        return []
    if not isinstance(data, list):
        return []
    return [item for item in data if isinstance(item, dict)]


def all_rf_signatures() -> list[dict[str, Any]]:
    """Return built-in and user-defined RF signatures."""
    return [*RF_SIGNATURES, *_load_user_signatures()]


def capture_to_signature(
    name: str,
    short_pulse: float,
    long_pulse: float,
    gap: float | None = None,
    modulation: str | None = None,
    file_name: str | None = None,
) -> dict[str, Any]:
    """Capture an unknown pulse pair as a reusable user signature."""
    signature = {
        "name": name.strip(),
        "file": file_name or "user_captured",
        "modulation": modulation or "UNKNOWN",
        "short_pulse": float(short_pulse),
        "long_pulse": float(long_pulse),
        "gap": None if gap is None else float(gap),
        "source": "Capture to Signature",
    }
    signatures = _load_user_signatures()
    signatures.append(signature)
    USER_SIGNATURES_FILE.parent.mkdir(parents=True, exist_ok=True)
    USER_SIGNATURES_FILE.write_text(json.dumps(signatures, indent=2), encoding="utf-8")
    return signature


def match_rf_signature(
    short_pulse: float | int | None,
    long_pulse: float | int | None,
    tolerance: float = 0.10,
) -> dict[str, Any] | None:
    """Return the first matching RF signature using pulse-width tolerance."""
    if short_pulse is None or long_pulse is None:
        return None

    observed_short = float(short_pulse)
    observed_long = float(long_pulse)

    for signature in all_rf_signatures():
        expected_short = signature.get("short_pulse")
        expected_long = signature.get("long_pulse")
        if expected_short is None or expected_long is None:
            continue
        if _within_tolerance(observed_short, float(expected_short), tolerance) and _within_tolerance(
            observed_long,
            float(expected_long),
            tolerance,
        ):
            return signature
    return None
